version: '3.8'

services:
  agenda-gol:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # stdin_open: true
    # tty: true
